[config]
version_check = false
fallback_color = "#00ff99"
caching = true

import_json_files = [
    "./keywords.json"
]

[templates.gtk3-settings]
input_path = "./templates/gtk-settings.ini"
output_path = "~/.config/gtk-3.0/settings.ini"
pre_hook = "[ -f ~/.config/gtk-3.0/settings.ini ] && chmod 644 ~/.config/gtk-3.0/settings.ini"
post_hook = "chmod 444 ~/.config/gtk-3.0/settings.ini"

[templates.gtk4-settings]
input_path = "./templates/gtk-settings.ini"
output_path = "~/.config/gtk-4.0/settings.ini"
pre_hook = "[ -f ~/.config/gtk-4.0/settings.ini ] && chmod 644 ~/.config/gtk-4.0/settings.ini"
post_hook = '''
    gsettings set org.gnome.desktop.interface gtk-theme "Materia-{{ mode }}";                        \
    gsettings set org.gnome.desktop.interface icon-theme "{{ icon_theme }}";                         \
    gsettings set org.gnome.desktop.interface font-name "{{ font_normal }}, {{ font_normal_size }}"; \
    gsettings set org.gnome.desktop.interface cursor-theme "{{ cursor_theme }}";                     \
    gsettings set org.gnome.desktop.interface cursor-size "{{ cursor_size }}";                       \
    gsettings set org.gnome.desktop.interface color-scheme "prefer-{{ mode }}";                      \
    chmod 444 ~/.config/gtk-4.0/settings.ini
'''

[templates.qt5ct]
input_path = "./templates/qt5ct.conf"
output_path = "~/.config/qt5ct/qt5ct.conf"
pre_hook = "[ -f ~/.config/qt5ct/qt5ct.conf ] && chmod 644 ~/.config/qt5ct/qt5ct.conf"
post_hook = "chmod 444 ~/.config/qt5ct/qt5ct.conf"

[templates.qt6ct]
input_path = "./templates/qt6ct.conf"
output_path = "~/.config/qt6ct/qt6ct.conf"
pre_hook = '''
    [ -f ~/.config/qt6ct/qt6ct.conf ] && chmod 644 ~/.config/qt6ct/qt6ct.conf;                 \
    [ -f ~/.config/Kvantum/kvantum.kvconfig ] && chmod 644 ~/.config/Kvantum/kvantum.kvconfig; \
    kvantummanager --set "Materia<* if {{ is_dark_mode }} *>Dark<* else *>Light<* endif *>";   \
    chmod 444 ~/.config/Kvantum/kvantum.kvconfig
'''
post_hook = "chmod 444 ~/.config/qt6ct/qt6ct.conf"
