theme = "dark_plus"

[editor]
mouse = true
middle-click-paste = true
auto-completion = true
path-completion = true
auto-format = true
preview-completion-insert = true
completion-trigger-len = 2
completion-replace = true
true-color = true
rulers = [80, 110]
bufferline = "always"
default-line-ending = "lf"
insert-final-newline = true
atomic-save = true
trim-final-newlines = true
trim-trailing-whitespace = true
editor-config = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator", "diagnostics"]
center = ["version-control", "workspace-diagnostics"]
right = ["selections", "register", "position", "file-encoding", "file-line-ending", "file-type"]

[editor.lsp]
enable = true

[editor.cursor-shape]
normal = "block"
insert = "underline"
select = "block"

[editor.whitespace]
render = "all"

[editor.indent-guides]
render = true
