"$schema" = 'https://starship.rs/config-schema.json'

format = '''$username@$hostname:$directory $git_branch$git_status
$shell $status$character '''
add_newline = false

[username]
format = "[$user]($style)"
style_user = "bright-green"
show_always = true

[hostname]
format = "[$hostname]($style)"
style = "bright-green"
ssh_only = false

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
read_only = "[readonly]"
style = "cyan"
read_only_style = "red"
truncate_to_repo = false

[git_branch]
format = "[\\[$branch\\]]($style)"
style = "purple"

[git_status]
format = "[\\[$all_status$ahead_behind\\]]($style)"
style = "bright-blue"
conflicted = "="
ahead = ">"
behind = "<"
diverged = "/"
up_to_date = ""
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = "~"
deleted = "x"
typechanged = "%"

[shell]
format = "$indicator"
disabled = false

[status]
format = "[\\[$status\\]]($style)"
style = "red"
disabled = false

[character]
format = "$symbol"
success_symbol = "[~>](green)"
error_symbol = "[>](red)"
